// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace BikeRental.Infrastructure.EfCore.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "BikeModels",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Type = table.Column<string>(type: "text", nullable: false),
                    WheelSizeInches = table.Column<double>(type: "double precision", nullable: false),
                    MaxPassengerWeightKg = table.Column<double>(type: "double precision", nullable: false),
                    BikeWeightKg = table.Column<double>(type: "double precision", nullable: false),
                    BrakeType = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    ModelYear = table.Column<int>(type: "integer", nullable: false),
                    HourlyPrice = table.Column<decimal>(type: "numeric(18,2)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BikeModels", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Renters",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    FullName = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                    PhoneNumber = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Renters", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Bikes",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    SerialNumber = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    Color = table.Column<string>(type: "character varying(30)", maxLength: 30, nullable: false),
                    BikeModelId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Bikes", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Bikes_BikeModels_BikeModelId",
                        column: x => x.BikeModelId,
                        principalTable: "BikeModels",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Rentals",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    BikeId = table.Column<int>(type: "integer", nullable: false),
                    RenterId = table.Column<int>(type: "integer", nullable: false),
                    RentStart = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    DurationHours = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Rentals", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Rentals_Bikes_BikeId",
                        column: x => x.BikeId,
                        principalTable: "Bikes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Rentals_Renters_RenterId",
                        column: x => x.RenterId,
                        principalTable: "Renters",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "BikeModels",
                columns: new[] { "Id", "BikeWeightKg", "BrakeType", "HourlyPrice", "MaxPassengerWeightKg", "ModelYear", "Name", "Type", "WheelSizeInches" },
                values: new object[,]
                {
                    { 1, 14.5, "Hydraulic Disc", 500.00m, 120.0, 2023, "Mountain King 2000", "Mountain", 29.0 },
                    { 2, 16.0, "V-Brake", 300.00m, 110.0, 2022, "City Glider", "City", 28.0 },
                    { 3, 9.5, "Mechanical Disc", 600.00m, 100.0, 2024, "Speed Demon", "Road", 28.0 },
                    { 4, 22.0, "Hydraulic Disc", 900.00m, 130.0, 2023, "Electro Bolt", "Electric", 27.5 },
                    { 5, 8.0, "Coaster", 150.00m, 50.0, 2021, "Little Rider", "Children", 20.0 },
                    { 6, 15.0, "Hydraulic Disc", 450.00m, 125.0, 2022, "Trail Master X", "Mountain", 27.5 },
                    { 7, 15.5, "Rim", 250.00m, 115.0, 2020, "Urban Commuter", "City", 28.0 },
                    { 8, 8.1999999999999993, "Rim", 700.00m, 95.0, 2023, "Aero Carbon", "Road", 28.0 },
                    { 9, 24.0, "Mechanical Disc", 850.00m, 120.0, 2022, "Volt City", "Electric", 26.0 },
                    { 10, 10.0, "V-Brake", 200.00m, 60.0, 2023, "Junior Racer", "Children", 24.0 }
                });

            migrationBuilder.InsertData(
                table: "Renters",
                columns: new[] { "Id", "FullName", "PhoneNumber" },
                values: new object[,]
                {
                    { 1, "Иванов Иван Иванович", "+79001112233" },
                    { 2, "Петров Петр Петрович", "+79002223344" },
                    { 3, "Сидоров Владимир Викторович", "+79003334455" },
                    { 4, "Кузнецова Анна Сергеевна", "+79004445566" },
                    { 5, "Смирнов Алексей Дмитриевич", "+79005556677" },
                    { 6, "Попова Мария Ивановна", "+79006667788" },
                    { 7, "Васильев Дмитрий Олегович", "+79007778899" },
                    { 8, "Соколов Сергей Павлович", "+79008889900" },
                    { 9, "Михайлова Елена Владимировна", "+79009990011" },
                    { 10, "Новиков Артем Игоревич", "+79000001122" }
                });

            migrationBuilder.InsertData(
                table: "Bikes",
                columns: new[] { "Id", "BikeModelId", "Color", "SerialNumber" },
                values: new object[,]
                {
                    { 1, 1, "Black", "SN-MTB-001" },
                    { 2, 2, "White", "SN-CTY-002" },
                    { 3, 3, "Red", "SN-RD-003" },
                    { 4, 4, "Blue", "SN-EL-004" },
                    { 5, 5, "Pink", "SN-CHD-005" },
                    { 6, 6, "Green", "SN-MTB-006" },
                    { 7, 7, "Grey", "SN-CTY-007" },
                    { 8, 8, "Yellow", "SN-RD-008" },
                    { 9, 9, "Matte Black", "SN-EL-009" },
                    { 10, 10, "Orange", "SN-CHD-010" }
                });

            migrationBuilder.InsertData(
                table: "Rentals",
                columns: new[] { "Id", "BikeId", "DurationHours", "RentStart", "RenterId" },
                values: new object[,]
                {
                    { 1, 1, 2, new DateTimeOffset(new DateTime(2026, 2, 2, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 1 },
                    { 2, 3, 5, new DateTimeOffset(new DateTime(2026, 2, 4, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 1 },
                    { 3, 2, 1, new DateTimeOffset(new DateTime(2026, 2, 5, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 2 },
                    { 4, 4, 3, new DateTimeOffset(new DateTime(2026, 2, 6, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 2 },
                    { 5, 1, 4, new DateTimeOffset(new DateTime(2026, 2, 7, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 3 },
                    { 6, 4, 24, new DateTimeOffset(new DateTime(2026, 2, 10, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 4 },
                    { 7, 5, 1, new DateTimeOffset(new DateTime(2026, 2, 11, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 5 },
                    { 8, 2, 2, new DateTimeOffset(new DateTime(2026, 2, 12, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 1 },
                    { 9, 6, 10, new DateTimeOffset(new DateTime(2026, 2, 12, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 6 },
                    { 10, 7, 1, new DateTimeOffset(new DateTime(2026, 2, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)), 7 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Bikes_BikeModelId",
                table: "Bikes",
                column: "BikeModelId");

            migrationBuilder.CreateIndex(
                name: "IX_Rentals_BikeId",
                table: "Rentals",
                column: "BikeId");

            migrationBuilder.CreateIndex(
                name: "IX_Rentals_RenterId",
                table: "Rentals",
                column: "RenterId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Rentals");

            migrationBuilder.DropTable(
                name: "Bikes");

            migrationBuilder.DropTable(
                name: "Renters");

            migrationBuilder.DropTable(
                name: "BikeModels");
        }
    }
}
