// <auto-generated />
using System;
using BikeRental.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikeRental.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BikeRentalDbContext))]
    partial class BikeRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikeRental.Domain.Model.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BikeModelId");

                    b.ToTable("Bikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BikeModelId = 1,
                            Color = "Black",
                            SerialNumber = "SN-MTB-001"
                        },
                        new
                        {
                            Id = 2,
                            BikeModelId = 2,
                            Color = "White",
                            SerialNumber = "SN-CTY-002"
                        },
                        new
                        {
                            Id = 3,
                            BikeModelId = 3,
                            Color = "Red",
                            SerialNumber = "SN-RD-003"
                        },
                        new
                        {
                            Id = 4,
                            BikeModelId = 4,
                            Color = "Blue",
                            SerialNumber = "SN-EL-004"
                        },
                        new
                        {
                            Id = 5,
                            BikeModelId = 5,
                            Color = "Pink",
                            SerialNumber = "SN-CHD-005"
                        },
                        new
                        {
                            Id = 6,
                            BikeModelId = 6,
                            Color = "Green",
                            SerialNumber = "SN-MTB-006"
                        },
                        new
                        {
                            Id = 7,
                            BikeModelId = 7,
                            Color = "Grey",
                            SerialNumber = "SN-CTY-007"
                        },
                        new
                        {
                            Id = 8,
                            BikeModelId = 8,
                            Color = "Yellow",
                            SerialNumber = "SN-RD-008"
                        },
                        new
                        {
                            Id = 9,
                            BikeModelId = 9,
                            Color = "Matte Black",
                            SerialNumber = "SN-EL-009"
                        },
                        new
                        {
                            Id = 10,
                            BikeModelId = 10,
                            Color = "Orange",
                            SerialNumber = "SN-CHD-010"
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Model.BikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BikeWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("BrakeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("HourlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("MaxPassengerWeightKg")
                        .HasColumnType("double precision");

                    b.Property<int>("ModelYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WheelSizeInches")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("BikeModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BikeWeightKg = 14.5,
                            BrakeType = "Hydraulic Disc",
                            HourlyPrice = 500.00m,
                            MaxPassengerWeightKg = 120.0,
                            ModelYear = 2023,
                            Name = "Mountain King 2000",
                            Type = "Mountain",
                            WheelSizeInches = 29.0
                        },
                        new
                        {
                            Id = 2,
                            BikeWeightKg = 16.0,
                            BrakeType = "V-Brake",
                            HourlyPrice = 300.00m,
                            MaxPassengerWeightKg = 110.0,
                            ModelYear = 2022,
                            Name = "City Glider",
                            Type = "City",
                            WheelSizeInches = 28.0
                        },
                        new
                        {
                            Id = 3,
                            BikeWeightKg = 9.5,
                            BrakeType = "Mechanical Disc",
                            HourlyPrice = 600.00m,
                            MaxPassengerWeightKg = 100.0,
                            ModelYear = 2024,
                            Name = "Speed Demon",
                            Type = "Road",
                            WheelSizeInches = 28.0
                        },
                        new
                        {
                            Id = 4,
                            BikeWeightKg = 22.0,
                            BrakeType = "Hydraulic Disc",
                            HourlyPrice = 900.00m,
                            MaxPassengerWeightKg = 130.0,
                            ModelYear = 2023,
                            Name = "Electro Bolt",
                            Type = "Electric",
                            WheelSizeInches = 27.5
                        },
                        new
                        {
                            Id = 5,
                            BikeWeightKg = 8.0,
                            BrakeType = "Coaster",
                            HourlyPrice = 150.00m,
                            MaxPassengerWeightKg = 50.0,
                            ModelYear = 2021,
                            Name = "Little Rider",
                            Type = "Children",
                            WheelSizeInches = 20.0
                        },
                        new
                        {
                            Id = 6,
                            BikeWeightKg = 15.0,
                            BrakeType = "Hydraulic Disc",
                            HourlyPrice = 450.00m,
                            MaxPassengerWeightKg = 125.0,
                            ModelYear = 2022,
                            Name = "Trail Master X",
                            Type = "Mountain",
                            WheelSizeInches = 27.5
                        },
                        new
                        {
                            Id = 7,
                            BikeWeightKg = 15.5,
                            BrakeType = "Rim",
                            HourlyPrice = 250.00m,
                            MaxPassengerWeightKg = 115.0,
                            ModelYear = 2020,
                            Name = "Urban Commuter",
                            Type = "City",
                            WheelSizeInches = 28.0
                        },
                        new
                        {
                            Id = 8,
                            BikeWeightKg = 8.1999999999999993,
                            BrakeType = "Rim",
                            HourlyPrice = 700.00m,
                            MaxPassengerWeightKg = 95.0,
                            ModelYear = 2023,
                            Name = "Aero Carbon",
                            Type = "Road",
                            WheelSizeInches = 28.0
                        },
                        new
                        {
                            Id = 9,
                            BikeWeightKg = 24.0,
                            BrakeType = "Mechanical Disc",
                            HourlyPrice = 850.00m,
                            MaxPassengerWeightKg = 120.0,
                            ModelYear = 2022,
                            Name = "Volt City",
                            Type = "Electric",
                            WheelSizeInches = 26.0
                        },
                        new
                        {
                            Id = 10,
                            BikeWeightKg = 10.0,
                            BrakeType = "V-Brake",
                            HourlyPrice = 200.00m,
                            MaxPassengerWeightKg = 60.0,
                            ModelYear = 2023,
                            Name = "Junior Racer",
                            Type = "Children",
                            WheelSizeInches = 24.0
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Model.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RentStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RenterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("RenterId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BikeId = 1,
                            DurationHours = 2,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 2, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 1
                        },
                        new
                        {
                            Id = 2,
                            BikeId = 3,
                            DurationHours = 5,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 4, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 1
                        },
                        new
                        {
                            Id = 3,
                            BikeId = 2,
                            DurationHours = 1,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 5, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 2
                        },
                        new
                        {
                            Id = 4,
                            BikeId = 4,
                            DurationHours = 3,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 6, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 2
                        },
                        new
                        {
                            Id = 5,
                            BikeId = 1,
                            DurationHours = 4,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 7, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 3
                        },
                        new
                        {
                            Id = 6,
                            BikeId = 4,
                            DurationHours = 24,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 10, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 4
                        },
                        new
                        {
                            Id = 7,
                            BikeId = 5,
                            DurationHours = 1,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 11, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 5
                        },
                        new
                        {
                            Id = 8,
                            BikeId = 2,
                            DurationHours = 2,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 12, 2, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 1
                        },
                        new
                        {
                            Id = 9,
                            BikeId = 6,
                            DurationHours = 10,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 12, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 6
                        },
                        new
                        {
                            Id = 10,
                            BikeId = 7,
                            DurationHours = 1,
                            RentStart = new DateTimeOffset(new DateTime(2026, 2, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RenterId = 7
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Model.Renter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Renters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Иванов Иван Иванович",
                            PhoneNumber = "+79001112233"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Петров Петр Петрович",
                            PhoneNumber = "+79002223344"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сидоров Владимир Викторович",
                            PhoneNumber = "+79003334455"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Кузнецова Анна Сергеевна",
                            PhoneNumber = "+79004445566"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Смирнов Алексей Дмитриевич",
                            PhoneNumber = "+79005556677"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Попова Мария Ивановна",
                            PhoneNumber = "+79006667788"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Васильев Дмитрий Олегович",
                            PhoneNumber = "+79007778899"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Соколов Сергей Павлович",
                            PhoneNumber = "+79008889900"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Михайлова Елена Владимировна",
                            PhoneNumber = "+79009990011"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Новиков Артем Игоревич",
                            PhoneNumber = "+79000001122"
                        });
                });

            modelBuilder.Entity("BikeRental.Domain.Model.Bike", b =>
                {
                    b.HasOne("BikeRental.Domain.Model.BikeModel", "Model")
                        .WithMany()
                        .HasForeignKey("BikeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRental.Domain.Model.Rental", b =>
                {
                    b.HasOne("BikeRental.Domain.Model.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeRental.Domain.Model.Renter", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Renter");
                });
#pragma warning restore 612, 618
        }
    }
}
